### ISSUE TITLE
Not working in Centos 7

### ISSUE THREAD

**Issue by hostingfuze** [duy13/vDDoS-Auto-Add#1]
[root@vDDoS ~]# vddos-autoadd [list] /etc/listdomains.txt

ERROR!

Please enter the correct syntax for the command: [[list]] ...

# Auto add for a domain:
 vddos-autoadd [domain] your-domain.com

**Comment by duy13** [comment]
```
[root@vDDoS ~]# vddos-autoadd list /etc/listdomains.txt
[root@vDDoS ~]# vddos-autoadd domain your-domain.com

```

Please remove [ ]
